version: "3.3"
services:
  cowrie:
    image: cowrie/cowrie
    ports:
      - "2222:2222"
      - "2323:2323"
    volumes:
      - ./cowrie/config/cowrie.cfg:/cowrie/cowrie-git/etc/cowrie.cfg
      - ./cowrie/config/userdb.txt:/cowrie/cowrie-git/etc/userdb.txt
      - ./cowrie/log/cowrie.json:/cowrie/cowrie-git/var/log/cowrie/cowrie.json
  elasticsearch:
    build: ./elasticsearch
    environment:
      ES_JAVA_OPTS: -Xms256m -Xmx256m
      discovery.type: single-node
    ports:
      - "9200:9200"
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - elasticsearch:/usr/share/elasticsearch/data
    networks:
      - elk
  kibana:
    build: ./kibana
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - "5601:5601"
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    depends_on:
      - elasticsearch
    networks:
      - elk
  logstash:
    build: ./logstash
    ports:
      - "5044:5044"
    volumes: 
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    environment:
      LS_JAVA_OPTS: -Xms256m -Xmx256m
    depends_on:
      - elasticsearch
    networks:
      - elk
  filebeat:      
    build: ./filebeat
    command:
      - "-e"
      - "--strict.perms=false"      
    volumes:
      - ./cowrie/log/cowrie.json:/var/log/cowrie/cowrie.json
      - ./filebeat/config/filebeat.yml:/usr/share/filebeat/filebeat.yml
    depends_on:
      - logstash  
    networks:
      - elk

volumes:
  elasticsearch:

networks:
  elk:
